# Configuration options for your blog - customise to taste
# This file contains no secret information, so can be stored in source control (unlike database.yml)
title: Live to Code
url:   http://livetocode.co.nz
author:
  name: Shevaun Coker        # For copyright notice and ATOM feeds
  email: shevaun.coker@gmail.com # Exception emails will go here, and it is used in ATOM feeds
  open_id:                  # These are used to login to the admin area
      - https://profiles.google.com/100753339495053265797

# Delete the following section if your site will not be acting as an OpenID delegate (http://wiki.openid.net/Delegation)
# If you're deploying with mongrel, make sure you read http://rhnh.net/2008/04/13/nginx-openid-delegation-and-yadis
open_id_delegation:
  server:   http://www.myopenid.com/server
  delegate: http://username.myopenid.com
